param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
)

$ErrorActionPreference = "Stop"

$generatedDir = Join-Path $Root "Engine\Foundation\Reflection"
$outHeader = Join-Path $generatedDir "CalyxObjectRegistry.generated.h"
$outSource = Join-Path $generatedDir "CalyxObjectRegistry.generated.cpp"
$scanRoots = @(
    (Join-Path $Root "Engine"),
    (Join-Path $Root "Game")
)

function Convert-ToCppString([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

function Write-IfChanged([string]$path, [string]$text) {
    if ((Test-Path $path) -and ((Get-Content $path -Raw) -eq $text)) {
        return
    }
    $dir = Split-Path $path -Parent
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
    }
    [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false))
}

function Get-RelativePathCompat([string]$basePath, [string]$targetPath) {
    $baseFull = [System.IO.Path]::GetFullPath($basePath)
    if (!$baseFull.EndsWith([System.IO.Path]::DirectorySeparatorChar)) {
        $baseFull += [System.IO.Path]::DirectorySeparatorChar
    }
    $targetFull = [System.IO.Path]::GetFullPath($targetPath)
    $baseUri = [System.Uri]::new($baseFull)
    $targetUri = [System.Uri]::new($targetFull)
    return [System.Uri]::UnescapeDataString($baseUri.MakeRelativeUri($targetUri).ToString()).Replace('/', '\')
}

$objectRegex = [regex]::new(
    'CALYX_OBJECT\s*\((?<meta>.*?)\)\s*class\s+(?<class>[A-Za-z_][A-Za-z0-9_]*)(?:\s+(?:final|abstract))*\s*:',
    [System.Text.RegularExpressions.RegexOptions]::Singleline
)

$entries = New-Object System.Collections.Generic.List[object]

foreach ($scanRoot in $scanRoots) {
    if (!(Test-Path $scanRoot)) {
        continue
    }

    Get-ChildItem -Path $scanRoot -Recurse -Filter *.h | ForEach-Object {
        $path = $_.FullName
        $text = Get-Content $path -Raw
        foreach ($match in $objectRegex.Matches($text)) {
            $meta = @{}
            foreach ($part in ($match.Groups["meta"].Value -replace "`r|`n", " ").Split(",")) {
                if (!$part.Contains("=")) {
                    continue
                }
                $pair = $part.Split("=", 2)
                $meta[$pair[0].Trim()] = $pair[1].Trim().Trim('"')
            }

            $className = $match.Groups["class"].Value
            $typeName = if ($meta.ContainsKey("TypeName")) { $meta["TypeName"] } else { $className }
            $displayName = if ($meta.ContainsKey("DisplayName")) { $meta["DisplayName"] } else { $typeName }
            $category = if ($meta.ContainsKey("Category")) { $meta["Category"] } else { "None" }
            $icon = if ($meta.ContainsKey("Icon")) { $meta["Icon"] } else { "UI/Tool/event.png" }
            $placeable = if ($meta.ContainsKey("Placeable")) { $meta["Placeable"].ToLower() -ne "false" } else { $true }
            $prefabEditable = if ($meta.ContainsKey("PrefabEditable")) { $meta["PrefabEditable"].ToLower() -eq "true" } else { $false }
            $prefabRoot = if ($meta.ContainsKey("PrefabRoot")) { $meta["PrefabRoot"].ToLower() -eq "true" } else { $false }
            $include = (Get-RelativePathCompat $Root $path).Replace('\', '/')

            $entries.Add([pscustomobject]@{
                ClassName = $className
                TypeName = $typeName
                DisplayName = $displayName
                Category = $category
                Icon = $icon
                Placeable = if ($placeable) { "true" } else { "false" }
                PrefabEditable = if ($prefabEditable) { "true" } else { "false" }
                PrefabRoot = if ($prefabRoot) { "true" } else { "false" }
                Include = $include
            })
        }
    }
}

$entries = $entries | Sort-Object TypeName

$header = @"
#pragma once

namespace CalyxEngine {
	void RegisterGeneratedSceneObjects();
}
"@

$includeLines = ($entries | ForEach-Object { "#include <$($_.Include)>" }) -join "`n"
$registrationBlocks = ($entries | ForEach-Object {
    $typeName = Convert-ToCppString $_.TypeName
    $displayName = Convert-ToCppString $_.DisplayName
    $icon = Convert-ToCppString $_.Icon
@"
		{
			SceneObjectClassDesc desc;
			desc.typeName = "$typeName";
			desc.displayName = "$displayName";
			desc.objectType = ObjectType::$($_.Category);
			desc.iconPath = "$icon";
			desc.placeable = $($_.Placeable);
			desc.prefabEditable = $($_.PrefabEditable);
			desc.prefabRoot = $($_.PrefabRoot);
			desc.ctor = std::make_unique<SceneCtor<$($_.ClassName)>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}
"@
}) -join "`n`n"

$source = @"
// This file is generated by Tools/Reflection/generate_reflection.ps1.
// Do not edit by hand.

#include <Engine/Foundation/Reflection/CalyxObjectRegistry.generated.h>

#include <Engine/Objects/3D/Actor/Registry/SceneObjectRegistry.h>

#include <memory>
#include <utility>

$includeLines

namespace CalyxEngine {
	void RegisterGeneratedSceneObjects() {
$registrationBlocks
	}
}
"@

Write-IfChanged $outHeader $header
Write-IfChanged $outSource $source
