from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCAN_ROOTS = [ROOT / "Engine", ROOT / "Game"]
GENERATED_DIR = ROOT / "Engine" / "Foundation" / "Reflection"
OUT_HEADER = GENERATED_DIR / "CalyxObjectRegistry.generated.h"
OUT_SOURCE = GENERATED_DIR / "CalyxObjectRegistry.generated.cpp"


OBJECT_RE = re.compile(
    r"CALYX_OBJECT\s*\((?P<meta>.*?)\)\s*"
    r"class\s+(?P<class>[A-Za-z_][A-Za-z0-9_]*)(?:\s+(?:final|abstract))*\s*:",
    re.DOTALL,
)


def parse_meta(raw: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for part in raw.replace("\n", " ").split(","):
        if "=" not in part:
            continue
        key, value = part.split("=", 1)
        values[key.strip()] = value.strip().strip('"')
    return values


def cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def rel_include(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover() -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for root in SCAN_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*.h"):
            text = path.read_text(encoding="utf-8", errors="ignore")
            for match in OBJECT_RE.finditer(text):
                meta = parse_meta(match.group("meta"))
                type_name = meta.get("TypeName", match.group("class"))
                display_name = meta.get("DisplayName", type_name)
                category = meta.get("Category", "None")
                icon = meta.get("Icon", "UI/Tool/event.png")
                placeable = meta.get("Placeable", "true").lower() != "false"
                prefab_editable = meta.get("PrefabEditable", "false").lower() == "true"
                prefab_root = meta.get("PrefabRoot", "false").lower() == "true"
                entries.append(
                    {
                        "class": match.group("class"),
                        "type_name": type_name,
                        "display_name": display_name,
                        "category": category,
                        "icon": icon,
                        "placeable": "true" if placeable else "false",
                        "prefab_editable": "true" if prefab_editable else "false",
                        "prefab_root": "true" if prefab_root else "false",
                        "include": rel_include(path),
                    }
                )
    return sorted(entries, key=lambda e: e["type_name"])


def write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def generate(entries: list[dict[str, str]]) -> None:
    header = """#pragma once

namespace CalyxEngine {
\tvoid RegisterGeneratedSceneObjects();
}
"""

    includes = "\n".join(f'#include <{entry["include"]}>' for entry in entries)
    registrations = []
    for entry in entries:
        registrations.append(
            f"""\t\t{{
\t\t\tSceneObjectClassDesc desc;
\t\t\tdesc.typeName = "{cpp_string(entry["type_name"])}";
\t\t\tdesc.displayName = "{cpp_string(entry["display_name"])}";
\t\t\tdesc.objectType = ObjectType::{entry["category"]};
\t\t\tdesc.iconPath = "{cpp_string(entry["icon"])}";
\t\t\tdesc.placeable = {entry["placeable"]};
\t\t\tdesc.prefabEditable = {entry["prefab_editable"]};
\t\t\tdesc.prefabRoot = {entry["prefab_root"]};
\t\t\tdesc.ctor = std::make_unique<SceneCtor<{entry["class"]}>>();
\t\t\tSceneObjectRegistry::Get().Register(std::move(desc));
\t\t}}"""
        )

    body = "\n\n".join(registrations)
    source = f"""// This file is generated by Tools/Reflection/generate_reflection.py.
// Do not edit by hand.

#include <Engine/Foundation/Reflection/CalyxObjectRegistry.generated.h>

#include <Engine/Objects/3D/Actor/Registry/SceneObjectRegistry.h>

#include <memory>
#include <utility>

{includes}

namespace CalyxEngine {{
\tvoid RegisterGeneratedSceneObjects() {{
{body}
\t}}
}}
"""

    write_if_changed(OUT_HEADER, header)
    write_if_changed(OUT_SOURCE, source)


def main() -> None:
    generate(discover())


if __name__ == "__main__":
    main()
