// This file is generated by Tools/Reflection/generate_reflection.ps1.
// Do not edit by hand.

#include <Engine/Foundation/Reflection/CalyxObjectRegistry.generated.h>

#include <Engine/Objects/3D/Actor/Registry/SceneObjectRegistry.h>

#include <memory>
#include <utility>

#include <Engine/Objects/Event/Camera/CameraEventObject.h>

namespace CalyxEngine {
	void RegisterGeneratedSceneObjects() {
		{
			SceneObjectClassDesc desc;
			desc.typeName = "CameraEventObject";
			desc.displayName = "Camera Event";
			desc.objectType = ObjectType::Event;
			desc.iconPath = "UI/Tool/event.png";
			desc.placeable = true;
			desc.ctor = std::make_unique<SceneCtor<CameraEventObject>>();
			SceneObjectRegistry::Get().Register(std::move(desc));
		}
	}
}